#! /usr/bin/env python
# encoding: utf-8

# /test/


bld.program(
    # TODO: want to add --deps gxml.deps
    packages = 'gio-2.0 gxml gee-0.8 posix',
    target = 'gxml_test',
    uselib = 'GTK GLIB GEE XML',
    use = 'gxml',
    source = ['AttrTest.vala', 'CharacterDataTest.vala', 'DocumentTest.vala', 'ElementTest.vala', 'GXmlTest.vala', 'NodeListTest.vala', 'TextTest.vala', 'ValaLibxml2Test.vala', 'XmlSerializableTest.vala', 'XNodeTest.vala'],
    vapi_dirs = ['../gxml', '../vapi']
    )
