#! /usr/bin/env python
# encoding: utf-8

# /test/


bld.program(
    # TODO: want to add --deps gxml.deps
    # packages = 'gtk+-2.0 gxml gee-1.0 libxml-2.0',
    packages = 'gio-2.0 gxml gee-1.0', # gee-1.0',
    target = 'gxml_test',
    uselib = 'GTK GLIB GEE XML',
    use = 'gxml',
    source = ['AttrTest.vala', 'CharacterDataTest.vala', 'DocumentTest.vala', 'ElementTest.vala', 'GXmlTest.vala', 'NodeListTest.vala', 'TextTest.vala', 'XNodeTest.vala'],
    vapi_dirs = '../gxml',
    vala_defines = ['DEBUG']
    # valaflags = ['-g']  # TODO: how do we communicate this?  Argh!
    )
