image: ubuntu:devel


stages:
  - build
  - deploy

variables:
  DEPENDENCIES: gcc gettext gtk-doc-tools make autoconf meson ninja-build
                libxml2-dev libglib2.0 libglib2.0-dev libglib2.0-bin
                valac libgee-0.8-dev gettext
                gnome-common libtool-bin
                gobject-introspection libgirepository1.0-dev valadoc
                yelp-tools iso-codes

  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt update
  - apt -y install $DEPENDENCIES

build-gxml:
  stage: build
  script:
  - meson _build
  - cd _build
  - ninja
  - meson test
  - ninja install

build-autotools:
  stage: build
  script:
  - ./autogen.sh --prefix=/usr
  - make
  - make check
  - make install

package-tar:
  stage: deploy
  script:
  - ./autogen.sh --prefix=/usr
  - make
  - make distcheck
  artifacts:
    paths:
      - ./gxml-*.tar.xz

pages:
  stage: deploy
  script:
  - meson _build
  - cd _build
  - ninja
  - mv docs/GXml-* ../public
  - cd ..
  - mv public/index.htm public/index.html


