image: ubuntu:devel


stages:
  - build

before_script:
  - apt update
  - apt-get install -y libxml2-dev libglib2.0-dev valac libgee-0.8-dev gettext meson

build-gxml:
  stage: build
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build test
  - ninja -C _build install

