image: debian:testing


stages:
  - build

before_script:
  - apt install libxml2-dev libglib2.0-dev valac meson

build-gxml:
  stage: build
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build test
  - ninja -C _build install

