image: debian:testing


stages:
  - build

before_script:
  - apt update
  - apt-get install -y libxml2-dev libglib2.0-dev valac libgee-0.8-dev gettext gobject-introspection gir1.2-glib-2.0 meson

build-gxml:
  stage: build
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build test
  - ninja -C _build install

