image: ubuntu:devel


stages:
  - build
  - deploy

variables:
  DEPENDENCIES: gcc gettext gtk-doc-tools make autoconf meson ninja-build
                libxml2-dev libglib2.0 libglib2.0-dev libglib2.0-bin
                valac libgee-0.8-dev gettext
                gnome-common libtool-bin
                gobject-introspection libgirepository1.0-dev valadoc
                yelp-tools iso-codes git

  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt update
  - apt -y install $DEPENDENCIES

build:
  stage: build
  script:
  - meson _build -Dintrospection=true -Ddocs=true
  - cd _build
  - ninja
  - meson test
  - ninja install

pages:
  stage: deploy
  script:
  - meson _build -Ddocs=true
  - cd _build
  - ninja
  - mv ../docs/site ../public
  - mv docs/GXml-* ../public/dev
  - cd ..
  - cp public/dev/index.htm public/dev/index.html
  artifacts:
    paths:
      - public


