option('introspection', type: 'feature', value: 'auto',
  description: 'Generate GObject Introspection metadata')
option('docs', type: 'feature', value: 'auto',
  description: 'Generate API documentation')
option('experimental', type: 'boolean', value: false,
  description: 'Build experimental classes')
