CC=gcc
CFLAGS=`pkg-config --cflags gxml gio-2.0` -g -Wall
LDFLAGS=`pkg-config --libs gxml gio-2.0`
PROGS=document_new document_new_minimal document_new_from_string document_new_from_file document_new_from_path document_save_to_path document_save_to_stream document_properties document_create node

all: $(PROGS)

clean:
	@rm $(PROGS) *.o *~ \#*\# output/*.xml 2>/dev/null || true

